# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-15 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_name', models.CharField(max_length=200)),
                ('bill_month', models.CharField(max_length=50)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
